# Environment Variables
# Set your environment variables here.
# Hyprland-specific variables can go in this file.
# System-wide variables can also be set in ~/.config/hypr/edit_here/source/environment_variables.conf

# This environment variable is set here to fix a warning caused by hyprland on boot.
env = XDG_CURRENT_DESKTOP,Hyprland
